/* Generated by Nim Compiler v1.4.2 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -DDISABLE_PREFIX -DFMI2_FUNCTION_PREFIX=MyModel_ -I/home/jose/src/nimlang/fmusdk-master/fmu20/src/shared/include -I/home/jose/src/nimlang/fmusdk-master/fmu20/src/shared/include/ -w -fmax-errors=5 -DMODEL_IDENTIFIER=\"inc\" -DMODEL_GUID=\"{8c4e810f-3df3-4a00-8276-176fa3c9f008}\" -DNUMBER_OF_REALS=0 -DNUMBER_OF_INTEGERS=1 -DNUMBER_OF_BOOLEANS=0 -DNUMBER_OF_STRINGS=0 -DNUMBER_OF_STATES=0 -DNUMBER_OF_EVENT_INDICATORS=0  -fPIC  -I/home/jose/.choosenim/toolchains/nim-1.4.2/lib -I/home/jose/src/fmi.nim/test/dq -o /home/jose/src/fmi.nim/test/dq/.cache/@minc.nim.c.o /home/jose/src/fmi.nim/test/dq/.cache/@minc.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include "/home/jose/src/nimlang/fmusdk-master/fmu20/src/models/fmuTemplate.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_TYPES */
typedef NU8 tyEnum_fmi2Type__F7Ba9a9csehhe1iYO9aozMO5Q;
typedef fmi2Boolean tyArray__cikP9cGhIEMMkw1XpRoouaQ[4];
typedef NU16 tyEnum_ModelState__phQ2HdK9b9boOflom5Leynpg;
typedef NU8 tyEnum_fmi2Status__0G9a4KIQ39aItE4tlUCACmug;

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, setStartValues)(ModelInstance* comp);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, calculateValues)(ModelInstance* comp);
N_LIB_PRIVATE N_NIMCALL(void, eventUpdate)(ModelInstance* comp, fmi2EventInfo* eventInfo, int timeEvent, int isNewEventIteration);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, setStartValues)(ModelInstance* comp) {
	nimfr_("setStartValues", "/home/jose/src/fmi.nim/test/dq/inc.nim");
	nimln_(22, "/home/jose/src/fmi.nim/test/dq/inc.nim");
	(*comp).i[((NI) 0)] = ((fmi2Integer) 1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, calculateValues)(ModelInstance* comp) {
	nimfr_("calculateValues", "/home/jose/src/fmi.nim/test/dq/inc.nim");
	nimln_(25, "/home/jose/src/fmi.nim/test/dq/inc.nim");
	{
		if (!((*comp).state == ((tyEnum_ModelState__phQ2HdK9b9boOflom5Leynpg) 4))) goto LA3_;
		nimln_(27, "/home/jose/src/fmi.nim/test/dq/inc.nim");
		(*comp).eventInfo.nextEventTimeDefined = ((fmi2Boolean) 1);
		nimln_(28, "/home/jose/src/fmi.nim/test/dq/inc.nim");
		(*comp).eventInfo.nextEventTime = ((NF)(1.0000000000000000e+00) + (NF)((*comp).time));
	}
	LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eventUpdate)(ModelInstance* comp, fmi2EventInfo* eventInfo, int timeEvent, int isNewEventIteration) {
	nimfr_("eventUpdate", "/home/jose/src/fmi.nim/test/dq/inc.nim");
	nimln_(31, "/home/jose/src/fmi.nim/test/dq/inc.nim");
	{
		NI TM__FLsth87a6UwB9cclkU39ctDQ_2;
		if (!!((timeEvent == ((NI32) 0)))) goto LA3_;
		nimln_(32, "/home/jose/src/fmi.nim/test/dq/inc.nim");
		if (nimAddInt((*comp).i[((NI) 0)], ((NI) 1), &TM__FLsth87a6UwB9cclkU39ctDQ_2)) { raiseOverflow(); };
		if (TM__FLsth87a6UwB9cclkU39ctDQ_2 < (-2147483647 -1) || TM__FLsth87a6UwB9cclkU39ctDQ_2 > 2147483647){ raiseOverflow(); }
		(*comp).i[((NI) 0)] = (fmi2Integer)(TM__FLsth87a6UwB9cclkU39ctDQ_2);
		nimln_(33, "/home/jose/src/fmi.nim/test/dq/inc.nim");
		{
			if (!((*comp).i[((NI) 0)] == ((NI32) 13))) goto LA7_;
			nimln_(34, "/home/jose/src/fmi.nim/test/dq/inc.nim");
			(*eventInfo).terminateSimulation = ((fmi2Boolean) 1);
			nimln_(35, "/home/jose/src/fmi.nim/test/dq/inc.nim");
			(*eventInfo).nextEventTimeDefined = ((fmi2Boolean) 0);
		}
		goto LA5_;
		LA7_: ;
		{
			nimln_(37, "/home/jose/src/fmi.nim/test/dq/inc.nim");
			(*eventInfo).nextEventTimeDefined = ((fmi2Boolean) 1);
			nimln_(38, "/home/jose/src/fmi.nim/test/dq/inc.nim");
			(*eventInfo).nextEventTime = ((NF)(1.0000000000000000e+00) + (NF)((*comp).time));
		}
		LA5_: ;
	}
	LA3_: ;
	popFrame();
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
	nimGC_setStackBottom(locals);
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	initStackBottomWith((void *)&inner);
	systemInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE void NIM_POSIX_INIT NimMainInit(void) {
	NimMain();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

