/* Generated by Nim Compiler v1.4.2 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3  -fPIC  -I/home/jose/.choosenim/toolchains/nim-1.4.2/lib -I/home/jose/src/fmi.nim/src/prueba -o /home/jose/src/fmi.nim/src/prueba/.cache/@mcosimulation.nim.c.o /home/jose/src/fmi.nim/src/prueba/.cache/@mcosimulation.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg;
typedef struct fmi2EventInfo fmi2EventInfo;

/* section: NIM_merge_TYPES */
typedef NU8 tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg;
typedef NU16 tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef double tyArray__qZCifDfMweXPZlPDmdFpTw[1];
typedef NI32 tyArray__zBLFLWYYZ1F9cWZALii7NkQ[1];
typedef NU8 tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew;
typedef NI32 tyArray__48IqrAYoce9a50c9bgEbuWGw[4];
struct fmi2EventInfo {
NI32 newDiscreteStatesNeeded;
NI32 terminateSimulation;
NI32 nominalsOfContinuousStatesChanged;
NI32 valuesOfContinuousStatesChanged;
NI32 nextEventTimeDefined;
NF nextEventTime;
};
struct tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w {
NF* r;
tyArray__zBLFLWYYZ1F9cWZALii7NkQ i;
NI32* b;
NCSTRING* s;
NI32* isPositive;
NF time;
NCSTRING instanceName;
tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew type_0;
NCSTRING GUID;
tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg* functions;
NI32 loggingOn;
tyArray__48IqrAYoce9a50c9bgEbuWGw logCategories;
void* componentEnvironment;
tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg state;
fmi2EventInfo eventInfo;
NI32 isDirtyValues;
NI32 isNewEventIteration;
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetRealInputDerivatives)(void* c, NU32* vr, size_t nvr, NI32* order, NF* value);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, invalidState__CFARkdpiNWnLYTkNRNqeNA)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, NCSTRING f, tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg statesExpected);
N_LIB_PRIVATE N_NIMCALL(void, filteredLog__lw3suybQ5yRVSDxTrBDwWg)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* instance, tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg status, int categoryIndex, NCSTRING message);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__UnG9acdsEfhNPutQSXglKKw)(NimStringDesc** result, size_t value, NimStringDesc* specifier);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2GetRealOutputDerivatives)(void* c, NU32* vr, size_t nvr, NI32* order, NF* value);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___hatOcKOmsgxQEFVbYh9cEeg)(NF* vr, NI n, NF val);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2CancelStep)(void* c);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2DoStep)(void* c, NF currentCommunicationPoint, NF communicationStepSize, NI32 noSetFMUStatePriorToCurrentPoint);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__F6AoShDCcKwxHedHsIa3bQ)(NimStringDesc** result, NF value, NimStringDesc* specifier);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__3zjq9csYPBcIN7AqvyU5ZLA)(NimStringDesc** result, NimStringDesc* value, NimStringDesc* specifier);
static N_INLINE(void, pluseq___rQEZChwoSrUAnV4ouVSb6Asystem)(NF* x, NF y);

/* section: NIM_merge_DATA */
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_2, "fmi2SetRealInputDerivatives: nvr= ", 34);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_3, "fmi2SetRealInputDerivatives: ignoring function call.\\nThis mode"
"l cannot interpolate inputs: canInterpolateInputs=\'", 114);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_4, "\'", 1);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_5, "fmi2GetRealOutputDerivatives: nvr= ", 35);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_6, "fmi2GetRealOutputDerivatives: ignoring function call.\\nThis mod"
"el cannot compute derivatives of outputs: MaxOutputDerivativeOrd"
"er=\'0\'", 133);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_8, "fmi2CancelStep: Can be called when fmi2DoStep returned fmi2Pend"
"ing.\\n This is not the case.", 91);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_9, "True", 4);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_10, "False", 5);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_11, "fmi2DoStep: \\ncurrentCommunicationPoint = ", 42);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_12, ", communicationStepSize = ", 26);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_13, ", noSetFMUStatePriorToCurrentPoint = fmi2", 41);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_14, "fmi2DoStep: communication step size must be > 0. Fount ", 55);
STRING_LITERAL(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_15, ".", 1);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetRealInputDerivatives)(void* c, NU32* vr, size_t nvr, NI32* order, NF* value) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	NimStringDesc* fmtRes;
	NimStringDesc* fmtRes_2;
	nimfr_("fmi2SetRealInputDerivatives", "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(22, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(23, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2SetRealInputDerivatives", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 2));
		if (!T3_) goto LA4_;
		nimln_(24, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(26, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(26, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	fmtRes = rawNewString(((NI) 49));
	fmtRes = resizeString(fmtRes, 34);
appendString(fmtRes, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_2));
	formatValue__UnG9acdsEfhNPutQSXglKKw((&fmtRes), nvr, ((NimStringDesc*) NIM_NIL));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes));
	nimln_(27, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(27, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	fmtRes_2 = rawNewString(((NI) 136));
	fmtRes_2 = resizeString(fmtRes_2, 114);
appendString(fmtRes_2, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_3));
	formatValue__UnG9acdsEfhNPutQSXglKKw((&fmtRes_2), ((NI) 0), ((NimStringDesc*) NIM_NIL));
	fmtRes_2 = resizeString(fmtRes_2, 1);
appendString(fmtRes_2, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_4));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), ((int) 1), nimToCStringConv(fmtRes_2));
	nimln_(28, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2GetRealOutputDerivatives)(void* c, NU32* vr, size_t nvr, NI32* order, NF* value) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	NimStringDesc* fmtRes;
	NimStringDesc* fmtRes_2;
	nimfr_("fmi2GetRealOutputDerivatives", "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(33, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(34, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2GetRealOutputDerivatives", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 32));
		if (!T3_) goto LA4_;
		nimln_(35, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(36, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(36, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	fmtRes = rawNewString(((NI) 50));
	fmtRes = resizeString(fmtRes, 35);
appendString(fmtRes, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_5));
	formatValue__UnG9acdsEfhNPutQSXglKKw((&fmtRes), nvr, ((NimStringDesc*) NIM_NIL));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes));
	nimln_(37, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(37, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	fmtRes_2 = rawNewString(((NI) 133));
	fmtRes_2 = resizeString(fmtRes_2, 133);
appendString(fmtRes_2, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_6));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), ((int) 1), nimToCStringConv(fmtRes_2));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(106, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
		i_2 = ((NI) 0);
		{
			nimln_(107, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
			while (1) {
				NI TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_7;
				if (!(i_2 < nvr)) goto LA8;
				nimln_(38, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
				i = i_2;
				nimln_(39, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
				X5BX5Deq___hatOcKOmsgxQEFVbYh9cEeg(value, i, 0.0);
				nimln_(109, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_7)) { raiseOverflow(); };
				i_2 = (NI)(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_7);
			} LA8: ;
		}
	}
	nimln_(40, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2CancelStep)(void* c) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	NimStringDesc* fmtRes;
	nimfr_("fmi2CancelStep", "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(44, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(45, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2CancelStep", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 64));
		if (!T3_) goto LA4_;
		nimln_(47, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(49, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), "fmi2CancelStep");
	nimln_(50, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(50, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	fmtRes = rawNewString(((NI) 91));
	fmtRes = resizeString(fmtRes, 91);
appendString(fmtRes, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_8));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), ((int) 1), nimToCStringConv(fmtRes));
	nimln_(52, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}
static N_INLINE(void, pluseq___rQEZChwoSrUAnV4ouVSb6Asystem)(NF* x, NF y) {
	nimfr_("+=", "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system.nim");
	nimln_(2646, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2DoStep)(void* c, NF currentCommunicationPoint, NF communicationStepSize, NI32 noSetFMUStatePriorToCurrentPoint) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	double h;
	NI n;
	tyArray__qZCifDfMweXPZlPDmdFpTw prevState;
	tyArray__qZCifDfMweXPZlPDmdFpTw prevEventIndicators;
	NI stateEvent;
	NI timeEvent;
	NimStringDesc* tmp;
	NimStringDesc* fmtRes;
	nimfr_("fmi2DoStep", "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(58, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(59, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	h = ((NF)(communicationStepSize) / (NF)(1.0000000000000000e+01));
	nimln_(61, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	n = ((NI) 10);
	nimZeroMem((void*)prevState, sizeof(tyArray__qZCifDfMweXPZlPDmdFpTw));
	nimZeroMem((void*)prevEventIndicators, sizeof(tyArray__qZCifDfMweXPZlPDmdFpTw));
	nimln_(64, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	stateEvent = ((NI) 0);
	nimln_(65, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	timeEvent = ((NI) 0);
	nimln_(67, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2DoStep", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 32));
		if (!T3_) goto LA4_;
		nimln_(68, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	tmp = (NimStringDesc*)0;
	nimln_(71, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	{
		if (!(((NI32) 1) < noSetFMUStatePriorToCurrentPoint)) goto LA8_;
		nimln_(72, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		tmp = copyString(((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_9));
	}
	goto LA6_;
	LA8_: ;
	{
		nimln_(74, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		tmp = copyString(((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_10));
	}
	LA6_: ;
	nimln_(75, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(75, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	fmtRes = rawNewString(((NI) 194));
	fmtRes = resizeString(fmtRes, 42);
appendString(fmtRes, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_11));
	formatValue__F6AoShDCcKwxHedHsIa3bQ((&fmtRes), currentCommunicationPoint, ((NimStringDesc*) NIM_NIL));
	fmtRes = resizeString(fmtRes, 26);
appendString(fmtRes, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_12));
	formatValue__F6AoShDCcKwxHedHsIa3bQ((&fmtRes), communicationStepSize, ((NimStringDesc*) NIM_NIL));
	fmtRes = resizeString(fmtRes, 41);
appendString(fmtRes, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_13));
	formatValue__3zjq9csYPBcIN7AqvyU5ZLA((&fmtRes), tmp, ((NimStringDesc*) NIM_NIL));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes));
	nimln_(77, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	{
		NimStringDesc* fmtRes_2;
		if (!(communicationStepSize <= 0.0)) goto LA13_;
		nimln_(78, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
		nimln_(79, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		fmtRes_2 = rawNewString(((NI) 89));
		fmtRes_2 = resizeString(fmtRes_2, 55);
appendString(fmtRes_2, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_14));
		formatValue__F6AoShDCcKwxHedHsIa3bQ((&fmtRes_2), communicationStepSize, ((NimStringDesc*) NIM_NIL));
		fmtRes_2 = resizeString(fmtRes_2, 1);
appendString(fmtRes_2, ((NimStringDesc*) &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_15));
		nimln_(78, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), ((int) 1), nimToCStringConv(fmtRes_2));
		nimln_(80, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		(*comp).state = ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 1024);
		nimln_(81, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA13_: ;
	nimln_(90, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	(*comp).time = currentCommunicationPoint;
	{
		NI k;
		NI i;
		k = (NI)0;
		nimln_(106, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
		i = ((NI) 0);
		{
			nimln_(107, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
			while (1) {
				NI TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_16;
				if (!(i < n)) goto LA17;
				nimln_(91, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
				k = i;
				nimln_(92, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
				pluseq___rQEZChwoSrUAnV4ouVSb6Asystem((&(*comp).time), h);
				nimln_(109, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
				if (nimAddInt(i, ((NI) 1), &TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_16)) { raiseOverflow(); };
				i = (NI)(TM__uEU9aZZZM9aK9c5e9bVpbUcNjw_16);
			} LA17: ;
		}
	}
	nimln_(138, "/home/jose/src/fmi.nim/src/prueba/cosimulation.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
