/* Generated by Nim Compiler v1.4.2 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3  -fPIC  -I/home/jose/.choosenim/toolchains/nim-1.4.2/lib -I/home/jose/src/fmi.nim/src/prueba -o /home/jose/src/fmi.nim/src/prueba/.cache/@mfmi2TypesPlatform.nim.c.o /home/jose/src/fmi.nim/src/prueba/.cache/@mfmi2TypesPlatform.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(NU32, X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA)(NU32* vr, NU64 n) {
	NU32 result;
	NU32* v;
	nimfr_("[]", "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	result = (NU32)0;
	nimln_(44, "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	v = ((NU32*) (vr));
	result = v[n];
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___tT1dykjMB9c0G0E9bG0MLrfw)(NI32* vr, NU64 n, NI32 val) {
	NI32* vr_2;
	nimfr_("[]=", "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	nimln_(60, "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	vr_2 = ((NI32*) (vr));
	nimln_(61, "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	vr_2[n] = val;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI32, X5BX5D___JS6FVIsrpB7DXYGSQvzqew)(NI32* vr, NU64 n) {
	NI32 result;
	NI32* v;
	nimfr_("[]", "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	result = (NI32)0;
	nimln_(56, "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	v = ((NI32*) (vr));
	result = v[n];
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, X5BX5D___GHO3LRaNeNnTNqGYrnXwqA)(NF* vr, NU64 n) {
	NF result;
	NF* v;
	nimfr_("[]", "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	result = (NF)0;
	nimln_(48, "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	v = ((NF*) (vr));
	result = v[n];
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___hatOcKOmsgxQEFVbYh9cEeg)(NF* vr, NI n, NF val) {
	NF* vr_2;
	nimfr_("[]=", "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	nimln_(52, "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	vr_2 = ((NF*) (vr));
	nimln_(53, "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	vr_2[n] = val;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___sYNVRtsTYXoEH7CAR7Inhg)(NF* vr, NU64 n, NF val) {
	NF* vr_2;
	nimfr_("[]=", "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	nimln_(52, "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	vr_2 = ((NF*) (vr));
	nimln_(53, "/home/jose/src/fmi.nim/src/prueba/fmi2TypesPlatform.nim");
	vr_2[n] = val;
	popFrame();
}
