/* Generated by Nim Compiler v1.4.2 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3  -fPIC  -I/home/jose/.choosenim/toolchains/nim-1.4.2/lib -I/home/jose/src/fmi.nim/src/prueba -o /home/jose/src/fmi.nim/src/prueba/.cache/@mmodelexchange.nim.c.o /home/jose/src/fmi.nim/src/prueba/.cache/@mmodelexchange.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w;
typedef struct tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg;
typedef struct fmi2EventInfo fmi2EventInfo;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;

/* section: NIM_merge_TYPES */
typedef NU8 tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg;
typedef NU16 tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg;
typedef NI32 tyArray__zBLFLWYYZ1F9cWZALii7NkQ[1];
typedef NU8 tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew;
typedef NI32 tyArray__48IqrAYoce9a50c9bgEbuWGw[4];
struct fmi2EventInfo {
NI32 newDiscreteStatesNeeded;
NI32 terminateSimulation;
NI32 nominalsOfContinuousStatesChanged;
NI32 valuesOfContinuousStatesChanged;
NI32 nextEventTimeDefined;
NF nextEventTime;
};
struct tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w {
NF* r;
tyArray__zBLFLWYYZ1F9cWZALii7NkQ i;
NI32* b;
NCSTRING* s;
NI32* isPositive;
NF time;
NCSTRING instanceName;
tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew type_0;
NCSTRING GUID;
tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg* functions;
NI32 loggingOn;
tyArray__48IqrAYoce9a50c9bgEbuWGw logCategories;
void* componentEnvironment;
tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg state;
fmi2EventInfo eventInfo;
NI32 isDirtyValues;
NI32 isNewEventIteration;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2EnterEventMode)(void* c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, invalidState__CFARkdpiNWnLYTkNRNqeNA)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, NCSTRING f, tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg statesExpected);
N_LIB_PRIVATE N_NIMCALL(void, filteredLog__lw3suybQ5yRVSDxTrBDwWg)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* instance, tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg status, int categoryIndex, NCSTRING message);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2NewDiscreteStates)(void* c, fmi2EventInfo* eventInfo);
N_LIB_PRIVATE N_NIMCALL(void, eventUpdate__L4BEeWQMThhFfqcZ4eG0Hg)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, fmi2EventInfo* eventInfo, NI timeEvent, NI isNewEventIteration);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2EnterContinuousTimeMode)(void* c);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2CompletedIntegratorStep)(void* c, NI32 noSetFMUStatePriorToCurrentPoint, NI32* enterEventMode, NI32* terminateSimulation);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nullPointer__XwrYJ3AKbQGv6XbV79casAA)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, NCSTRING f, NCSTRING arg, void* p);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetTime)(void* c, NF time);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetContinuousStates)(void* c, NF* x, size_t nx);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, invalidNumber__ecYAxsbLzTqP8en2Xizgww)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, NCSTRING f, NCSTRING arg, int n, int nExpected);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2GetDerivatives)(void* c, NF* derivatives, size_t nx);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2GetEventIndicators)(void* c, NF* eventIndicators, size_t ni);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2GetContinuousStates)(void* c, NF* states, size_t nx);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2GetNominalsOfContinuousStates)(void* c, NF* x_nominal, size_t nx);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__fFZs9aygbVmQlR35NW07Gbg)(NimStringDesc** result, size_t value, NimStringDesc* specifier);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___sYNVRtsTYXoEH7CAR7Inhg)(NF* vr, NU64 n, NF val);

/* section: NIM_merge_DATA */
STRING_LITERAL(TM__bAaP1VblLJpBfxCGmk9aAMw_2, "fmi2GetNominalContinuousStates: x_nominal[0..", 45);
STRING_LITERAL(TM__bAaP1VblLJpBfxCGmk9aAMw_3, "] = 1.0", 7);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2EnterEventMode)(void* c) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	nimfr_("fmi2EnterEventMode", "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(13, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(14, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2EnterEventMode", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 8));
		if (!T3_) goto LA4_;
		nimln_(15, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(16, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), "fmi2EnterEventMode");
	nimln_(18, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*comp).state = ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 8);
	nimln_(19, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*comp).isNewEventIteration = ((NI32) 1);
	nimln_(20, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2NewDiscreteStates)(void* c, fmi2EventInfo* eventInfo) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	int timeEvent;
	nimfr_("fmi2NewDiscreteStates", "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(24, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(25, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	timeEvent = ((int) 0);
	nimln_(26, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2NewDiscreteStates", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 8));
		if (!T3_) goto LA4_;
		nimln_(27, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(28, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), "fmi2NewDiscreteStates");
	nimln_(30, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*comp).eventInfo.newDiscreteStatesNeeded = ((NI32) 0);
	nimln_(31, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*comp).eventInfo.terminateSimulation = ((NI32) 0);
	nimln_(32, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*comp).eventInfo.nominalsOfContinuousStatesChanged = ((NI32) 0);
	nimln_(33, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*comp).eventInfo.valuesOfContinuousStatesChanged = ((NI32) 0);
	nimln_(35, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = (((NI32) 0) < (*comp).eventInfo.nextEventTimeDefined);
		if (!(T8_)) goto LA9_;
		T8_ = ((*comp).eventInfo.nextEventTime <= (*comp).time);
		LA9_: ;
		if (!T8_) goto LA10_;
		nimln_(36, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		timeEvent = ((int) 1);
	}
	LA10_: ;
	nimln_(38, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	eventUpdate__L4BEeWQMThhFfqcZ4eG0Hg(comp, (&(*comp).eventInfo), ((NI) (timeEvent)), ((NI) ((*comp).isNewEventIteration)));
	nimln_(39, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*comp).isNewEventIteration = ((NI32) 0);
	nimln_(42, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*eventInfo).newDiscreteStatesNeeded = (*comp).eventInfo.newDiscreteStatesNeeded;
	nimln_(43, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*eventInfo).terminateSimulation = (*comp).eventInfo.terminateSimulation;
	nimln_(44, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*eventInfo).nominalsOfContinuousStatesChanged = (*comp).eventInfo.nominalsOfContinuousStatesChanged;
	nimln_(45, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*eventInfo).valuesOfContinuousStatesChanged = (*comp).eventInfo.valuesOfContinuousStatesChanged;
	nimln_(46, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*eventInfo).nextEventTimeDefined = (*comp).eventInfo.nextEventTimeDefined;
	nimln_(47, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*eventInfo).nextEventTime = (*comp).eventInfo.nextEventTime;
	nimln_(49, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2EnterContinuousTimeMode)(void* c) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	nimfr_("fmi2EnterContinuousTimeMode", "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(53, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(54, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2EnterContinuousTimeMode", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 8));
		if (!T3_) goto LA4_;
		nimln_(55, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(56, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), "fmi2EnterContinuousTimeMode");
	nimln_(58, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*comp).state = ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 16);
	nimln_(59, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2CompletedIntegratorStep)(void* c, NI32 noSetFMUStatePriorToCurrentPoint, NI32* enterEventMode, NI32* terminateSimulation) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	nimfr_("fmi2CompletedIntegratorStep", "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(66, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(67, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2CompletedIntegratorStep", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 16));
		if (!T3_) goto LA4_;
		nimln_(68, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(69, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2CompletedIntegratorStep", "enterEventMode", ((void*) (enterEventMode)));
		if (!T8_) goto LA9_;
		nimln_(70, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA9_: ;
	nimln_(71, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2CompletedIntegratorStep", "terminateSimulation", ((void*) (terminateSimulation)));
		if (!T13_) goto LA14_;
		nimln_(72, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA14_: ;
	nimln_(73, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), "fmi2CompletedIntegratorStep");
	nimln_(75, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*enterEventMode) = ((NI32) 0);
	nimln_(76, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*terminateSimulation) = ((NI32) 0);
	nimln_(77, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetTime)(void* c, NF time) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	nimfr_("fmi2SetTime", "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(82, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(83, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2SetTime", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 8));
		if (!T3_) goto LA4_;
		nimln_(84, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(85, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), "fmi2SetTime: time={time:%.16g}");
	nimln_(86, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	(*comp).time = time;
	nimln_(87, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetContinuousStates)(void* c, NF* x, size_t nx) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	nimfr_("fmi2SetContinuousStates", "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(91, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(93, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2SetContinuousStates", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 16));
		if (!T3_) goto LA4_;
		nimln_(94, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(95, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T8_;
		if (nx > (size_t)(((int) 2147483647))){ raiseRangeErrorNoArgs(); }
		T8_ = (NIM_BOOL)0;
		T8_ = invalidNumber__ecYAxsbLzTqP8en2Xizgww(comp, "fmi2SetContinuousStates", "nx", ((int) (nx)), ((int) 0));
		if (!T8_) goto LA9_;
		nimln_(96, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA9_: ;
	nimln_(97, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2SetContinuousStates", "x[]", ((void*) (x)));
		if (!T13_) goto LA14_;
		nimln_(98, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA14_: ;
	nimln_(105, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2GetDerivatives)(void* c, NF* derivatives, size_t nx) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	nimfr_("fmi2GetDerivatives", "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(111, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(112, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2GetDerivatives", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 8));
		if (!T3_) goto LA4_;
		nimln_(113, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(114, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T8_;
		if (nx > (size_t)(((int) 2147483647))){ raiseRangeErrorNoArgs(); }
		T8_ = (NIM_BOOL)0;
		T8_ = invalidNumber__ecYAxsbLzTqP8en2Xizgww(comp, "fmi2GetDerivatives", "nx", ((int) (nx)), ((int) 0));
		if (!T8_) goto LA9_;
		nimln_(115, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA9_: ;
	nimln_(116, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2GetDerivatives", "derivatives[]", ((void*) (derivatives)));
		if (!T13_) goto LA14_;
		nimln_(117, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA14_: ;
	nimln_(124, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2GetEventIndicators)(void* c, NF* eventIndicators, size_t ni) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	nimfr_("fmi2GetEventIndicators", "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(130, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(131, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2GetEventIndicators", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 4));
		if (!T3_) goto LA4_;
		nimln_(132, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(133, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T8_;
		if (ni > (size_t)(((int) 2147483647))){ raiseRangeErrorNoArgs(); }
		T8_ = (NIM_BOOL)0;
		T8_ = invalidNumber__ecYAxsbLzTqP8en2Xizgww(comp, "fmi2GetEventIndicators", "ni", ((int) (ni)), ((int) 0));
		if (!T8_) goto LA9_;
		nimln_(134, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA9_: ;
	nimln_(140, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2GetContinuousStates)(void* c, NF* states, size_t nx) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	nimfr_("fmi2GetContinuousStates", "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(145, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(146, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2GetContinuousStates", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 4));
		if (!T3_) goto LA4_;
		nimln_(147, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(148, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T8_;
		if (nx > (size_t)(((int) 2147483647))){ raiseRangeErrorNoArgs(); }
		T8_ = (NIM_BOOL)0;
		T8_ = invalidNumber__ecYAxsbLzTqP8en2Xizgww(comp, "fmi2GetContinuousStates", "nx", ((int) (nx)), ((int) 0));
		if (!T8_) goto LA9_;
		nimln_(149, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA9_: ;
	nimln_(150, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2GetContinuousStates", "states[]", ((void*) (states)));
		if (!T13_) goto LA14_;
		nimln_(151, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA14_: ;
	nimln_(158, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2GetNominalsOfContinuousStates)(void* c, NF* x_nominal, size_t nx) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	NimStringDesc* fmtRes;
	nimfr_("fmi2GetNominalsOfContinuousStates", "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(164, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(165, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2GetNominalsOfContinuousStates", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 2));
		if (!T3_) goto LA4_;
		nimln_(166, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(167, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T8_;
		if (nx > (size_t)(((int) 2147483647))){ raiseRangeErrorNoArgs(); }
		T8_ = (NIM_BOOL)0;
		T8_ = invalidNumber__ecYAxsbLzTqP8en2Xizgww(comp, "fmi2GetNominalContinuousStates", "nx", ((int) (nx)), ((int) 0));
		if (!T8_) goto LA9_;
		nimln_(168, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA9_: ;
	nimln_(169, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2GetNominalContinuousStates", "x_nominal[]", ((void*) (x_nominal)));
		if (!T13_) goto LA14_;
		nimln_(170, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA14_: ;
	nimln_(171, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(171, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	fmtRes = rawNewString(((NI) 68));
	fmtRes = resizeString(fmtRes, 45);
appendString(fmtRes, ((NimStringDesc*) &TM__bAaP1VblLJpBfxCGmk9aAMw_2));
	nimln_(550, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/core/macros.nim");
	nimln_(171, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	formatValue__fFZs9aygbVmQlR35NW07Gbg((&fmtRes), (NU)((NU64)(nx) - (NU64)(((NU) 1))), ((NimStringDesc*) NIM_NIL));
	fmtRes = resizeString(fmtRes, 7);
appendString(fmtRes, ((NimStringDesc*) &TM__bAaP1VblLJpBfxCGmk9aAMw_3));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes));
	{
		NU64 i;
		NU64 colontmp_;
		NU64 res;
		i = (NU64)0;
		colontmp_ = (NU64)0;
		nimln_(172, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
		colontmp_ = ((NU64) (nx));
		nimln_(115, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
		res = 0ULL;
		{
			nimln_(116, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
			while (1) {
				if (!((NU64)(res) < (NU64)(colontmp_))) goto LA18;
				nimln_(172, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
				i = res;
				nimln_(173, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
				X5BX5Deq___sYNVRtsTYXoEH7CAR7Inhg(x_nominal, i, 1.0000000000000000e+00);
				nimln_(118, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
				res += ((NI) 1);
			} LA18: ;
		}
	}
	nimln_(174, "/home/jose/src/fmi.nim/src/prueba/modelexchange.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
