/* Generated by Nim Compiler v1.4.2 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3  -fPIC  -I/home/jose/.choosenim/toolchains/nim-1.4.2/lib -I/home/jose/src/fmi.nim/src/prueba -o /home/jose/src/fmi.nim/src/prueba/.cache/@mmodelinstance.nim.c.o /home/jose/src/fmi.nim/src/prueba/.cache/@mmodelinstance.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w;
typedef struct fmi2EventInfo fmi2EventInfo;

/* section: NIM_merge_TYPES */
typedef NU8 tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew;
typedef NU8 tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* a1, NCSTRING a2, tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg a3, NCSTRING a4, NCSTRING a5, void* ClE_0);
void* ClE_0;
} tyProc__ihdMnMKg5uf38WyS4C7wEw;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (unsigned int a1, unsigned int a2, void* ClE_0);
void* ClE_0;
} tyProc__ir12mkfU9bAk1e8MSGk2ZxQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* a1, void* ClE_0);
void* ClE_0;
} tyProc__uMUlmGrxGbyKfim0kpddgQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* a1, tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg a2, void* ClE_0);
void* ClE_0;
} tyProc__dOs5nk6FftN1ND9bueDuSMw;
struct tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg {
tyProc__ihdMnMKg5uf38WyS4C7wEw logger;
tyProc__ir12mkfU9bAk1e8MSGk2ZxQ allocateMemory;
tyProc__uMUlmGrxGbyKfim0kpddgQ freeMemory;
tyProc__dOs5nk6FftN1ND9bueDuSMw stepFinished;
void* componentEnvironment;
};
typedef N_CLOSURE_PTR(void, TM__ntFm3MbQAv5kaneEPmcJMw_2) (void* a1, NCSTRING a2, tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg a3, NCSTRING a4, NCSTRING a5);
typedef N_CLOSURE_PTR(void, TM__ntFm3MbQAv5kaneEPmcJMw_3) (void* a1, NCSTRING a2, tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg a3, NCSTRING a4, NCSTRING a5);
typedef N_CLOSURE_PTR(void, TM__ntFm3MbQAv5kaneEPmcJMw_4) (void* a1, NCSTRING a2, tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg a3, NCSTRING a4, NCSTRING a5);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CLOSURE_PTR(void, TM__ntFm3MbQAv5kaneEPmcJMw_9) (void* a1, NCSTRING a2, tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg a3, NCSTRING a4, NCSTRING a5);
typedef NI32 tyArray__zBLFLWYYZ1F9cWZALii7NkQ[1];
typedef NI32 tyArray__48IqrAYoce9a50c9bgEbuWGw[4];
typedef NU16 tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg;
struct fmi2EventInfo {
NI32 newDiscreteStatesNeeded;
NI32 terminateSimulation;
NI32 nominalsOfContinuousStatesChanged;
NI32 valuesOfContinuousStatesChanged;
NI32 nextEventTimeDefined;
NF nextEventTime;
};
struct tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w {
NF* r;
tyArray__zBLFLWYYZ1F9cWZALii7NkQ i;
NI32* b;
NCSTRING* s;
NI32* isPositive;
NF time;
NCSTRING instanceName;
tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew type_0;
NCSTRING GUID;
tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg* functions;
NI32 loggingOn;
tyArray__48IqrAYoce9a50c9bgEbuWGw logCategories;
void* componentEnvironment;
tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg state;
fmi2EventInfo eventInfo;
NI32 isDirtyValues;
NI32 isNewEventIteration;
};
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef N_CLOSURE_PTR(void, TM__ntFm3MbQAv5kaneEPmcJMw_13) (void* a1);
typedef N_CLOSURE_PTR(void, TM__ntFm3MbQAv5kaneEPmcJMw_14) (void* a1);
typedef N_CLOSURE_PTR(void, TM__ntFm3MbQAv5kaneEPmcJMw_15) (void* a1);
typedef N_CLOSURE_PTR(void, TM__ntFm3MbQAv5kaneEPmcJMw_16) (void* a1);

/* section: NIM_merge_PROC_HEADERS */
N_LIB_EXPORT N_CDECL(void*, fmi2Instantiate)(NCSTRING instanceName, tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew fmuType, NCSTRING fmuGUID, NCSTRING fmuResourceLocation, tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg* functions, NI32 visible, NI32 loggingOn);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(NI, nimCStrLen)(NCSTRING a);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__3zjq9csYPBcIN7AqvyU5ZLA)(NimStringDesc** result, NimStringDesc* value, NimStringDesc* specifier);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, setStartValues__g4m7TFvWvrc0TdD6kxuUaQ_2)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp);
N_LIB_PRIVATE N_NIMCALL(void, filteredLog__lw3suybQ5yRVSDxTrBDwWg)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* instance, tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg status, int categoryIndex, NCSTRING message);
N_LIB_PRIVATE N_NIMCALL(void, add__8FwY5enLGB0dFerO6Ny9caw)(NimStringDesc** x, NCSTRING y);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, setString)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, NU32 vr, NCSTRING value);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetString)(void* c, NU32* vr, size_t nvr, NCSTRING* value);
N_LIB_EXPORT N_CDECL(void, fmi2FreeInstance)(void* c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, invalidState__CFARkdpiNWnLYTkNRNqeNA)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, NCSTRING f, tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg statesExpected);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetDebugLogging)(void* c, NI32 loggingOn, size_t nCategories, void* categories);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);

/* section: NIM_merge_DATA */
STRING_LITERAL(TM__ntFm3MbQAv5kaneEPmcJMw_5, "{8c4e810f-3df3-4a00-8276-176fa3c9f008}", 38);
STRING_LITERAL(TM__ntFm3MbQAv5kaneEPmcJMw_6, "fmi2Instantiate: Wrong GUID ", 28);
STRING_LITERAL(TM__ntFm3MbQAv5kaneEPmcJMw_7, ". Expected ", 11);
STRING_LITERAL(TM__ntFm3MbQAv5kaneEPmcJMw_8, ".", 1);
STRING_LITERAL(TM__ntFm3MbQAv5kaneEPmcJMw_10, "fmi2Instantiate: GUID=", 22);
STRING_LITERAL(TM__ntFm3MbQAv5kaneEPmcJMw_12, "Initiated!!", 11);
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__ntFm3MbQAv5kaneEPmcJMw_11 = {((NimStringDesc*) &TM__ntFm3MbQAv5kaneEPmcJMw_12)}
;

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(NI, nimCStrLen)(NCSTRING a) {
	NI result;
	size_t T1_;
	result = (NI)0;
	T1_ = (size_t)0;
	T1_ = strlen(a);
	result = ((NI) (T1_));
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
	nimfr_("eqStrings", "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/strmantle"
".nim");
{	result = (NIM_BOOL)0;
	nimln_(24, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/strmantle"
".nim");
	alen = (a ? a->Sup.len : 0);
	nimln_(25, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/strmantle"
".nim");
	blen = (b ? b->Sup.len : 0);
	nimln_(26, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/strmantle"
".nim");
	{
		if (!(alen == blen)) goto LA3_;
		nimln_(27, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/strmantle"
".nim");
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		nimln_(28, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/strmantle"
".nim");
		result = equalMem__9bGgqEk7RXXl6eqM9c1HdELAsystem(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(void*, fmi2Instantiate)(NCSTRING instanceName, tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew fmuType, NCSTRING fmuGUID, NCSTRING fmuResourceLocation, tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg* functions, NI32 visible, NI32 loggingOn) {
	void* result;
	tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg f;
	union { tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg* source; tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg dest; } LOC1;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w comp;
	NimStringDesc* fmtRes_2;
	nimfr_("fmi2Instantiate", "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
{	result = (void*)0;
	nimZeroMem((void*)(&f), sizeof(tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg));
	nimln_(82, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	LOC1.source = functions;
	nimCopyMem((void*)(&f), (NIM_CONST void*)(&LOC1.dest), sizeof(f));
	nimln_(86, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		if (!(f.logger.ClP_0 == 0)) goto LA4_;
		nimln_(87, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(89, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = (f.allocateMemory.ClP_0 == 0);
		if (T8_) goto LA9_;
		T8_ = (f.freeMemory.ClP_0 == 0);
		LA9_: ;
		if (!T8_) goto LA10_;
		nimln_(90, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		f.logger.ClE_0? f.logger.ClP_0((*functions).componentEnvironment, instanceName, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), "error", "fmi2Instantiate: Missing callback function.", f.logger.ClE_0):((TM__ntFm3MbQAv5kaneEPmcJMw_2)(f.logger.ClP_0))((*functions).componentEnvironment, instanceName, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), "error", "fmi2Instantiate: Missing callback function.");
		nimln_(92, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA10_: ;
	nimln_(94, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = (instanceName == 0);
		if (T14_) goto LA15_;
		T14_ = ((instanceName ? nimCStrLen(instanceName) : 0) == ((NI) 0));
		LA15_: ;
		if (!T14_) goto LA16_;
		nimln_(95, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		f.logger.ClE_0? f.logger.ClP_0((*functions).componentEnvironment, "\?", ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), "error", "fmi2Instantiate: Missing instance name.", f.logger.ClE_0):((TM__ntFm3MbQAv5kaneEPmcJMw_3)(f.logger.ClP_0))((*functions).componentEnvironment, "\?", ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), "error", "fmi2Instantiate: Missing instance name.");
		nimln_(97, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA16_: ;
	nimln_(99, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		NIM_BOOL T20_;
		T20_ = (NIM_BOOL)0;
		T20_ = (fmuGUID == 0);
		if (T20_) goto LA21_;
		T20_ = ((fmuGUID ? nimCStrLen(fmuGUID) : 0) == ((NI) 0));
		LA21_: ;
		if (!T20_) goto LA22_;
		nimln_(100, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		f.logger.ClE_0? f.logger.ClP_0((*functions).componentEnvironment, instanceName, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), "error", "fmi2Instantiate: Missing GUID.", f.logger.ClE_0):((TM__ntFm3MbQAv5kaneEPmcJMw_4)(f.logger.ClP_0))((*functions).componentEnvironment, instanceName, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), "error", "fmi2Instantiate: Missing GUID.");
		nimln_(102, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA22_: ;
	nimln_(104, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		NimStringDesc* T26_;
		NimStringDesc* fmtRes;
		NimStringDesc* T29_;
		T26_ = (NimStringDesc*)0;
		T26_ = cstrToNimstr(fmuGUID);
		if (!!(eqStrings(T26_, ((NimStringDesc*) &TM__ntFm3MbQAv5kaneEPmcJMw_5)))) goto LA27_;
		nimln_(105, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
		nimln_(106, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		fmtRes = rawNewString(((NI) 84));
		fmtRes = resizeString(fmtRes, 28);
appendString(fmtRes, ((NimStringDesc*) &TM__ntFm3MbQAv5kaneEPmcJMw_6));
		nimln_(550, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/core/macros.nim");
		T29_ = (NimStringDesc*)0;
		T29_ = cstrToNimstr(fmuGUID);
		nimln_(106, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		formatValue__3zjq9csYPBcIN7AqvyU5ZLA((&fmtRes), T29_, ((NimStringDesc*) NIM_NIL));
		fmtRes = resizeString(fmtRes, 11);
appendString(fmtRes, ((NimStringDesc*) &TM__ntFm3MbQAv5kaneEPmcJMw_7));
		formatValue__3zjq9csYPBcIN7AqvyU5ZLA((&fmtRes), ((NimStringDesc*) &TM__ntFm3MbQAv5kaneEPmcJMw_5), ((NimStringDesc*) NIM_NIL));
		fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM__ntFm3MbQAv5kaneEPmcJMw_8));
		f.logger.ClE_0? f.logger.ClP_0((*functions).componentEnvironment, instanceName, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), "error", nimToCStringConv(fmtRes), f.logger.ClE_0):((TM__ntFm3MbQAv5kaneEPmcJMw_9)(f.logger.ClP_0))((*functions).componentEnvironment, instanceName, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3), "error", nimToCStringConv(fmtRes));
		nimln_(107, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA27_: ;
	nimZeroMem((void*)(&comp), sizeof(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w));
	nimln_(136, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.time = 0.0;
	nimln_(137, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.instanceName = instanceName;
	nimln_(138, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.type_0 = fmuType;
	nimln_(139, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.GUID = fmuGUID;
	nimln_(143, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.functions = functions;
	nimln_(145, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.componentEnvironment = f.componentEnvironment;
	nimln_(147, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.loggingOn = loggingOn;
	nimln_(149, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.state = ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 2);
	nimln_(151, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	setStartValues__g4m7TFvWvrc0TdD6kxuUaQ_2((&comp));
	nimln_(152, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.isDirtyValues = ((NI32) 1);
	nimln_(153, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.isNewEventIteration = ((NI32) 0);
	nimln_(155, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.eventInfo.newDiscreteStatesNeeded = ((NI32) 0);
	nimln_(156, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.eventInfo.terminateSimulation = ((NI32) 0);
	nimln_(157, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.eventInfo.nominalsOfContinuousStatesChanged = ((NI32) 0);
	nimln_(158, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.eventInfo.valuesOfContinuousStatesChanged = ((NI32) 0);
	nimln_(159, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.eventInfo.nextEventTimeDefined = ((NI32) 0);
	nimln_(160, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp.eventInfo.nextEventTime = 0.0;
	nimln_(161, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(161, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	fmtRes_2 = rawNewString(((NI) 41));
	fmtRes_2 = resizeString(fmtRes_2, 22);
appendString(fmtRes_2, ((NimStringDesc*) &TM__ntFm3MbQAv5kaneEPmcJMw_10));
	nimln_(621, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	add__8FwY5enLGB0dFerO6Ny9caw((&fmtRes_2), fmuGUID);
	nimln_(161, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	filteredLog__lw3suybQ5yRVSDxTrBDwWg((&comp), ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes_2));
	nimln_(162, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	echoBinSafe(TM__ntFm3MbQAv5kaneEPmcJMw_11, 1);
	nimln_(163, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	result = ((void*) ((&comp)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, setString)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, NU32 vr, NCSTRING value) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	nimfr_("setString", "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(170, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	result = fmi2SetString(((void*) (comp)), (&vr), ((size_t) 1), (&value));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(void, fmi2FreeInstance)(void* c) {
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	nimfr_("fmi2FreeInstance", "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
{	nimln_(181, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(182, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		if (!(comp == 0)) goto LA3_;
		nimln_(183, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(184, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2FreeInstance", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 2));
		if (!T7_) goto LA8_;
		nimln_(185, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		goto BeforeRet_;
	}
	LA8_: ;
	nimln_(186, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), "fmi2FreeInstance");
	nimln_(188, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		if (!!(((*comp).r == 0))) goto LA12_;
		nimln_(189, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		(*(*comp).functions).freeMemory.ClE_0? (*(*comp).functions).freeMemory.ClP_0(((void*) ((*comp).r)), (*(*comp).functions).freeMemory.ClE_0):((TM__ntFm3MbQAv5kaneEPmcJMw_13)((*(*comp).functions).freeMemory.ClP_0))(((void*) ((*comp).r)));
	}
	LA12_: ;
	nimln_(192, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		if (!!(((*comp).b == 0))) goto LA16_;
		nimln_(193, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		(*(*comp).functions).freeMemory.ClE_0? (*(*comp).functions).freeMemory.ClP_0(((void*) ((*comp).b)), (*(*comp).functions).freeMemory.ClE_0):((TM__ntFm3MbQAv5kaneEPmcJMw_14)((*(*comp).functions).freeMemory.ClP_0))(((void*) ((*comp).b)));
	}
	LA16_: ;
	nimln_(194, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		if (!!(((*comp).s == 0))) goto LA20_;
		nimln_(200, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		(*(*comp).functions).freeMemory.ClE_0? (*(*comp).functions).freeMemory.ClP_0(((void*) ((*comp).s)), (*(*comp).functions).freeMemory.ClE_0):((TM__ntFm3MbQAv5kaneEPmcJMw_15)((*(*comp).functions).freeMemory.ClP_0))(((void*) ((*comp).s)));
	}
	LA20_: ;
	nimln_(211, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	(*(*comp).functions).freeMemory.ClE_0? (*(*comp).functions).freeMemory.ClP_0(((void*) (comp)), (*(*comp).functions).freeMemory.ClE_0):((TM__ntFm3MbQAv5kaneEPmcJMw_16)((*(*comp).functions).freeMemory.ClP_0))(((void*) (comp)));
	}BeforeRet_: ;
	popFrame();
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetDebugLogging)(void* c, NI32 loggingOn, size_t nCategories, void* categories) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	nimfr_("fmi2SetDebugLogging", "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(228, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(229, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2SetDebugLogging", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 2));
		if (!T3_) goto LA4_;
		nimln_(230, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(231, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	(*comp).loggingOn = loggingOn;
	nimln_(232, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), "fmi2SetDebugLogging");
	{
		NI j;
		NI i;
		j = (NI)0;
		nimln_(106, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
		i = ((NI) 0);
		{
			nimln_(107, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
			while (1) {
				NI TM__ntFm3MbQAv5kaneEPmcJMw_17;
				if (!(i < ((NI) 4))) goto LA8;
				nimln_(235, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
				j = i;
				if ((NU)(j) > (NU)(3)){ raiseIndexError2(j, 3); }
				nimln_(236, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
				(*comp).logCategories[(j)- 0] = ((NI32) 0);
				nimln_(109, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
				if (nimAddInt(i, ((NI) 1), &TM__ntFm3MbQAv5kaneEPmcJMw_17)) { raiseOverflow(); };
				i = (NI)(TM__ntFm3MbQAv5kaneEPmcJMw_17);
			} LA8: ;
		}
	}
	nimln_(238, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	{
		if (!(nCategories == ((NU) 0))) goto LA11_;
		{
			NI j_2;
			NI i_2;
			j_2 = (NI)0;
			nimln_(106, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
			i_2 = ((NI) 0);
			{
				nimln_(107, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
				while (1) {
					NI TM__ntFm3MbQAv5kaneEPmcJMw_18;
					if (!(i_2 < ((NI) 4))) goto LA15;
					nimln_(240, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
					j_2 = i_2;
					if ((NU)(j_2) > (NU)(3)){ raiseIndexError2(j_2, 3); }
					nimln_(241, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
					(*comp).logCategories[(j_2)- 0] = loggingOn;
					nimln_(109, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
					if (nimAddInt(i_2, ((NI) 1), &TM__ntFm3MbQAv5kaneEPmcJMw_18)) { raiseOverflow(); };
					i_2 = (NI)(TM__ntFm3MbQAv5kaneEPmcJMw_18);
				} LA15: ;
			}
		}
	}
	goto LA9_;
	LA11_: ;
	{
		{
			NU64 i_3;
			NU64 colontmp_;
			NU64 res;
			i_3 = (NU64)0;
			colontmp_ = (NU64)0;
			nimln_(245, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
			colontmp_ = ((NU64) (nCategories));
			nimln_(115, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
			res = 0ULL;
			{
				nimln_(116, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
				while (1) {
					NI32 categoryFound;
					if (!((NU64)(res) < (NU64)(colontmp_))) goto LA19;
					nimln_(245, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
					i_3 = res;
					nimln_(246, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
					categoryFound = ((NI32) 0);
					nimln_(118, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
					res += ((NI) 1);
				} LA19: ;
			}
		}
	}
	LA9_: ;
	nimln_(262, "/home/jose/src/fmi.nim/src/prueba/modelinstance.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
