/* Generated by Nim Compiler v1.4.2 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3  -fPIC  -I/home/jose/.choosenim/toolchains/nim-1.4.2/lib -I/home/jose/src/fmi.nim/src/prueba -o /home/jose/src/fmi.nim/src/prueba/.cache/@mmodel.nim.c.o /home/jose/src/fmi.nim/src/prueba/.cache/@mmodel.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w;
typedef struct tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg;
typedef struct fmi2EventInfo fmi2EventInfo;

/* section: NIM_merge_TYPES */
typedef NI32 tyArray__zBLFLWYYZ1F9cWZALii7NkQ[1];
typedef NU8 tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew;
typedef NI32 tyArray__48IqrAYoce9a50c9bgEbuWGw[4];
typedef NU16 tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg;
struct fmi2EventInfo {
NI32 newDiscreteStatesNeeded;
NI32 terminateSimulation;
NI32 nominalsOfContinuousStatesChanged;
NI32 valuesOfContinuousStatesChanged;
NI32 nextEventTimeDefined;
NF nextEventTime;
};
struct tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w {
NF* r;
tyArray__zBLFLWYYZ1F9cWZALii7NkQ i;
NI32* b;
NCSTRING* s;
NI32* isPositive;
NF time;
NCSTRING instanceName;
tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew type_0;
NCSTRING GUID;
tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg* functions;
NI32 loggingOn;
tyArray__48IqrAYoce9a50c9bgEbuWGw logCategories;
void* componentEnvironment;
tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg state;
fmi2EventInfo eventInfo;
NI32 isDirtyValues;
NI32 isNewEventIteration;
};

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, calculateValues__g4m7TFvWvrc0TdD6kxuUaQ)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp) {
	nimfr_("calculateValues", "/home/jose/src/fmi.nim/src/prueba/model.nim");
	nimln_(29, "/home/jose/src/fmi.nim/src/prueba/model.nim");
	{
		if (!((*comp).state == ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 4))) goto LA3_;
		nimln_(31, "/home/jose/src/fmi.nim/src/prueba/model.nim");
		(*comp).eventInfo.nextEventTimeDefined = ((NI32) 1);
		nimln_(32, "/home/jose/src/fmi.nim/src/prueba/model.nim");
		(*comp).eventInfo.nextEventTime = ((NF)(1.0000000000000000e+00) + (NF)((*comp).time));
	}
	LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setStartValues__g4m7TFvWvrc0TdD6kxuUaQ_2)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp) {
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w c;
	union { tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* source; tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w dest; } LOC1;
	nimfr_("setStartValues", "/home/jose/src/fmi.nim/src/prueba/model.nim");
	nimln_(23, "/home/jose/src/fmi.nim/src/prueba/model.nim");
	LOC1.source = comp;
	c = LOC1.dest;
	nimln_(25, "/home/jose/src/fmi.nim/src/prueba/model.nim");
	c.i[(((NI) 0))- 0] = ((NI32) 1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eventUpdate__L4BEeWQMThhFfqcZ4eG0Hg)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, fmi2EventInfo* eventInfo, NI timeEvent, NI isNewEventIteration) {
	nimfr_("eventUpdate", "/home/jose/src/fmi.nim/src/prueba/model.nim");
	nimln_(36, "/home/jose/src/fmi.nim/src/prueba/model.nim");
	{
		NI TM__EgSibMSoRYjBPhM5DELmOg_2;
		if (!!((timeEvent == ((NI) 0)))) goto LA3_;
		nimln_(37, "/home/jose/src/fmi.nim/src/prueba/model.nim");
		if (nimAddInt((*comp).i[(((NI) 0))- 0], ((NI) 1), &TM__EgSibMSoRYjBPhM5DELmOg_2)) { raiseOverflow(); };
		if (TM__EgSibMSoRYjBPhM5DELmOg_2 < (-2147483647 -1) || TM__EgSibMSoRYjBPhM5DELmOg_2 > 2147483647){ raiseOverflow(); }
		(*comp).i[(((NI) 0))- 0] = (NI32)(TM__EgSibMSoRYjBPhM5DELmOg_2);
		nimln_(38, "/home/jose/src/fmi.nim/src/prueba/model.nim");
		{
			if (!((*comp).i[(((NI) 0))- 0] == ((NI32) 13))) goto LA7_;
			nimln_(39, "/home/jose/src/fmi.nim/src/prueba/model.nim");
			(*eventInfo).terminateSimulation = ((NI32) 1);
			nimln_(40, "/home/jose/src/fmi.nim/src/prueba/model.nim");
			(*eventInfo).nextEventTimeDefined = ((NI32) 0);
		}
		goto LA5_;
		LA7_: ;
		{
			nimln_(42, "/home/jose/src/fmi.nim/src/prueba/model.nim");
			(*eventInfo).nextEventTimeDefined = ((NI32) 1);
			nimln_(43, "/home/jose/src/fmi.nim/src/prueba/model.nim");
			(*eventInfo).nextEventTime = ((NF)(1.0000000000000000e+00) + (NF)((*comp).time));
		}
		LA5_: ;
	}
	LA3_: ;
	popFrame();
}
