/* Generated by Nim Compiler v1.4.2 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3  -fPIC  -I/home/jose/.choosenim/toolchains/nim-1.4.2/lib -I/home/jose/src/fmi.nim/src/prueba -o /home/jose/src/fmi.nim/src/prueba/.cache/@msetters.nim.c.o /home/jose/src/fmi.nim/src/prueba/.cache/@msetters.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg;
typedef struct fmi2EventInfo fmi2EventInfo;

/* section: NIM_merge_TYPES */
typedef NU8 tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg;
typedef NU16 tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI32 tyArray__zBLFLWYYZ1F9cWZALii7NkQ[1];
typedef NU8 tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew;
typedef NI32 tyArray__48IqrAYoce9a50c9bgEbuWGw[4];
struct fmi2EventInfo {
NI32 newDiscreteStatesNeeded;
NI32 terminateSimulation;
NI32 nominalsOfContinuousStatesChanged;
NI32 valuesOfContinuousStatesChanged;
NI32 nextEventTimeDefined;
NF nextEventTime;
};
struct tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w {
NF* r;
tyArray__zBLFLWYYZ1F9cWZALii7NkQ i;
NI32* b;
NCSTRING* s;
NI32* isPositive;
NF time;
NCSTRING instanceName;
tyEnum_fmi2Type__fvJT52iMO9bHIEUsKT6J0Ew type_0;
NCSTRING GUID;
tyObject_fmi2CallbackFunctions__dmYHUw9cjWrTLW4e9aaT6AYg* functions;
NI32 loggingOn;
tyArray__48IqrAYoce9a50c9bgEbuWGw logCategories;
void* componentEnvironment;
tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg state;
fmi2EventInfo eventInfo;
NI32 isDirtyValues;
NI32 isNewEventIteration;
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetReal)(void* c, NU32* vr, size_t nvr, NF* value);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, invalidState__CFARkdpiNWnLYTkNRNqeNA)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, NCSTRING f, tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg statesExpected);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nullPointer__XwrYJ3AKbQGv6XbV79casAA)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, NCSTRING f, NCSTRING arg, void* p);
N_LIB_PRIVATE N_NIMCALL(void, filteredLog__lw3suybQ5yRVSDxTrBDwWg)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* instance, tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg status, int categoryIndex, NCSTRING message);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__fFZs9aygbVmQlR35NW07Gbg)(NimStringDesc** result, size_t value, NimStringDesc* specifier);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, vrOutOfRange__UhcMWpzGPUrXCK9cH9a20zjg)(tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp, NCSTRING f, NU32 vr, int end_0);
N_LIB_PRIVATE N_NIMCALL(NU32, X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA)(NU32* vr, NU64 n);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__C31L3FTGCD9awB6j0rwrtEQ)(NimStringDesc** result, NU32 value, NimStringDesc* specifier);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__F6AoShDCcKwxHedHsIa3bQ)(NimStringDesc** result, NF value, NimStringDesc* specifier);
N_LIB_PRIVATE N_NIMCALL(NF, X5BX5D___GHO3LRaNeNnTNqGYrnXwqA)(NF* vr, NU64 n);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetInteger)(void* c, NU32* vr, size_t nvr, NI32* value);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__FHGegxCkY6EscNTF2OFusw)(NimStringDesc** result, int value, NimStringDesc* specifier);
N_LIB_PRIVATE N_NIMCALL(NI32, X5BX5D___JS6FVIsrpB7DXYGSQvzqew)(NI32* vr, NU64 n);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetBoolean)(void* c, NU32* vr, size_t nvr, NI32* value);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__3zjq9csYPBcIN7AqvyU5ZLA)(NimStringDesc** result, NimStringDesc* value, NimStringDesc* specifier);
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetString)(void* c, NU32* vr, size_t nvr, NCSTRING* value);

/* section: NIM_merge_DATA */
STRING_LITERAL(TM__2S5MsC5486JvBpMWRxckKQ_2, "fmi2SetReal: nvr = ", 19);
STRING_LITERAL(TM__2S5MsC5486JvBpMWRxckKQ_3, "fmi2SetReal: #r", 15);
STRING_LITERAL(TM__2S5MsC5486JvBpMWRxckKQ_4, "# = ", 4);
STRING_LITERAL(TM__2S5MsC5486JvBpMWRxckKQ_5, "fmi2SetInteger: nvr = ", 22);
STRING_LITERAL(TM__2S5MsC5486JvBpMWRxckKQ_6, "fmi2SetInteger: #i", 18);
STRING_LITERAL(TM__2S5MsC5486JvBpMWRxckKQ_7, "fmi2SetBoolean: nvr = ", 22);
STRING_LITERAL(TM__2S5MsC5486JvBpMWRxckKQ_8, "true", 4);
STRING_LITERAL(TM__2S5MsC5486JvBpMWRxckKQ_9, "false", 5);
STRING_LITERAL(TM__2S5MsC5486JvBpMWRxckKQ_10, "fmi2SetBoolean: #b", 18);
STRING_LITERAL(TM__2S5MsC5486JvBpMWRxckKQ_11, "fmi2SetString: nvr = ", 21);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetReal)(void* c, NU32* vr, size_t nvr, NF* value) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	NI i;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	NimStringDesc* fmtRes;
	nimfr_("fmi2SetReal", "/home/jose/src/fmi.nim/src/prueba/setters.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	i = (NI)0;
	nimln_(10, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(11, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2SetReal", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 2));
		if (!T3_) goto LA4_;
		nimln_(12, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(13, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = ((NU64)(((NU) 0)) < (NU64)(nvr));
		if (!(T8_)) goto LA9_;
		T8_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2SetReal", "vr[]", ((void*) (vr)));
		LA9_: ;
		if (!T8_) goto LA10_;
		nimln_(14, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA10_: ;
	nimln_(15, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = ((NU64)(((NU) 0)) < (NU64)(nvr));
		if (!(T14_)) goto LA15_;
		T14_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2SetReal", "value[]", ((void*) (value)));
		LA15_: ;
		if (!T14_) goto LA16_;
		nimln_(16, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA16_: ;
	nimln_(17, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(17, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	fmtRes = rawNewString(((NI) 34));
	fmtRes = resizeString(fmtRes, 19);
appendString(fmtRes, ((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_2));
	formatValue__fFZs9aygbVmQlR35NW07Gbg((&fmtRes), nvr, ((NimStringDesc*) NIM_NIL));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes));
	{
		NU64 i_2;
		NU64 colontmp_;
		NU64 res;
		i_2 = (NU64)0;
		colontmp_ = (NU64)0;
		nimln_(19, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		colontmp_ = ((NU64) (nvr));
		nimln_(115, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
		res = 0ULL;
		{
			nimln_(116, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
			while (1) {
				NimStringDesc* fmtRes_2;
				NU32 T27_;
				NF T28_;
				NU32 T29_;
				if (!((NU64)(res) < (NU64)(colontmp_))) goto LA20;
				nimln_(19, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				i_2 = res;
				nimln_(20, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				{
					NU32 T23_;
					NIM_BOOL T24_;
					T23_ = (NU32)0;
					T23_ = X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA(vr, i_2);
					T24_ = (NIM_BOOL)0;
					T24_ = vrOutOfRange__UhcMWpzGPUrXCK9cH9a20zjg(comp, "fmi2SetReal", T23_, ((int) 0));
					if (!T24_) goto LA25_;
					nimln_(21, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
					result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
					goto BeforeRet_;
				}
				LA25_: ;
				nimln_(22, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
				nimln_(22, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				fmtRes_2 = rawNewString(((NI) 56));
				fmtRes_2 = resizeString(fmtRes_2, 15);
appendString(fmtRes_2, ((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_3));
				nimln_(550, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/core/macros.nim");
				T27_ = (NU32)0;
				T27_ = X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA(vr, i_2);
				nimln_(22, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				formatValue__C31L3FTGCD9awB6j0rwrtEQ((&fmtRes_2), T27_, ((NimStringDesc*) NIM_NIL));
				fmtRes_2 = resizeString(fmtRes_2, 4);
appendString(fmtRes_2, ((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_4));
				nimln_(550, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/core/macros.nim");
				T28_ = (NF)0;
				T28_ = X5BX5D___GHO3LRaNeNnTNqGYrnXwqA(value, i_2);
				nimln_(22, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				formatValue__F6AoShDCcKwxHedHsIa3bQ((&fmtRes_2), T28_, ((NimStringDesc*) NIM_NIL));
				filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes_2));
				nimln_(23, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				T29_ = (NU32)0;
				T29_ = X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA(vr, i_2);
				(*comp).r[T29_] = X5BX5D___GHO3LRaNeNnTNqGYrnXwqA(value, i_2);
				nimln_(118, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
				res += ((NI) 1);
			} LA20: ;
		}
	}
	nimln_(25, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		if (!((NU64)(((NU) 0)) < (NU64)(nvr))) goto LA32_;
		nimln_(26, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		(*comp).isDirtyValues = ((NI32) 1);
	}
	LA32_: ;
	nimln_(27, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetInteger)(void* c, NU32* vr, size_t nvr, NI32* value) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	NI i;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	NimStringDesc* fmtRes;
	nimfr_("fmi2SetInteger", "/home/jose/src/fmi.nim/src/prueba/setters.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	i = (NI)0;
	nimln_(33, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(34, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2SetInteger", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 2));
		if (!T3_) goto LA4_;
		nimln_(35, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(36, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = ((NU64)(((NU) 0)) < (NU64)(nvr));
		if (!(T8_)) goto LA9_;
		T8_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2SetInteger", "vr[]", ((void*) (vr)));
		LA9_: ;
		if (!T8_) goto LA10_;
		nimln_(37, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA10_: ;
	nimln_(38, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = ((NU64)(((NU) 0)) < (NU64)(nvr));
		if (!(T14_)) goto LA15_;
		T14_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2SetInteger", "value[]", ((void*) (value)));
		LA15_: ;
		if (!T14_) goto LA16_;
		nimln_(39, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA16_: ;
	nimln_(40, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(40, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	fmtRes = rawNewString(((NI) 37));
	fmtRes = resizeString(fmtRes, 22);
appendString(fmtRes, ((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_5));
	formatValue__fFZs9aygbVmQlR35NW07Gbg((&fmtRes), nvr, ((NimStringDesc*) NIM_NIL));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes));
	{
		NU64 i_2;
		NU64 colontmp_;
		NU64 res;
		i_2 = (NU64)0;
		colontmp_ = (NU64)0;
		nimln_(42, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		colontmp_ = ((NU64) (nvr));
		nimln_(115, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
		res = 0ULL;
		{
			nimln_(116, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
			while (1) {
				NimStringDesc* fmtRes_2;
				NU32 T27_;
				NI32 T28_;
				NU32 T29_;
				if (!((NU64)(res) < (NU64)(colontmp_))) goto LA20;
				nimln_(42, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				i_2 = res;
				nimln_(43, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				{
					NU32 T23_;
					NIM_BOOL T24_;
					T23_ = (NU32)0;
					T23_ = X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA(vr, i_2);
					T24_ = (NIM_BOOL)0;
					T24_ = vrOutOfRange__UhcMWpzGPUrXCK9cH9a20zjg(comp, "fmi2SetInteger", T23_, ((int) 1));
					if (!T24_) goto LA25_;
					nimln_(44, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
					result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
					goto BeforeRet_;
				}
				LA25_: ;
				nimln_(45, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
				nimln_(45, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				fmtRes_2 = rawNewString(((NI) 59));
				fmtRes_2 = resizeString(fmtRes_2, 18);
appendString(fmtRes_2, ((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_6));
				nimln_(550, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/core/macros.nim");
				T27_ = (NU32)0;
				T27_ = X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA(vr, i_2);
				nimln_(45, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				formatValue__C31L3FTGCD9awB6j0rwrtEQ((&fmtRes_2), T27_, ((NimStringDesc*) NIM_NIL));
				fmtRes_2 = resizeString(fmtRes_2, 4);
appendString(fmtRes_2, ((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_4));
				nimln_(550, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/core/macros.nim");
				T28_ = (NI32)0;
				T28_ = X5BX5D___JS6FVIsrpB7DXYGSQvzqew(value, i_2);
				nimln_(45, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				formatValue__FHGegxCkY6EscNTF2OFusw((&fmtRes_2), T28_, ((NimStringDesc*) NIM_NIL));
				filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes_2));
				nimln_(46, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				T29_ = (NU32)0;
				T29_ = X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA(vr, i_2);
				if ((NU)(T29_) > (NU)(0)){ raiseIndexError2(T29_, 0); }
				(*comp).i[(T29_)- 0] = X5BX5D___JS6FVIsrpB7DXYGSQvzqew(value, i_2);
				nimln_(118, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
				res += ((NI) 1);
			} LA20: ;
		}
	}
	nimln_(48, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		if (!((NU64)(((NU) 0)) < (NU64)(nvr))) goto LA32_;
		nimln_(49, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		(*comp).isDirtyValues = ((NI32) 1);
	}
	LA32_: ;
	nimln_(50, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetBoolean)(void* c, NU32* vr, size_t nvr, NI32* value) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	NI i;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	NimStringDesc* fmtRes;
	nimfr_("fmi2SetBoolean", "/home/jose/src/fmi.nim/src/prueba/setters.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	i = (NI)0;
	nimln_(56, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(57, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2SetBoolean", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 2));
		if (!T3_) goto LA4_;
		nimln_(58, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(59, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = ((NU64)(((NU) 0)) < (NU64)(nvr));
		if (!(T8_)) goto LA9_;
		T8_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2SetBoolean", "vr[]", ((void*) (vr)));
		LA9_: ;
		if (!T8_) goto LA10_;
		nimln_(60, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA10_: ;
	nimln_(61, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = ((NU64)(((NU) 0)) < (NU64)(nvr));
		if (!(T14_)) goto LA15_;
		T14_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2SetBoolean", "value[]", ((void*) (value)));
		LA15_: ;
		if (!T14_) goto LA16_;
		nimln_(62, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA16_: ;
	nimln_(63, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(63, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	fmtRes = rawNewString(((NI) 37));
	fmtRes = resizeString(fmtRes, 22);
appendString(fmtRes, ((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_7));
	formatValue__fFZs9aygbVmQlR35NW07Gbg((&fmtRes), nvr, ((NimStringDesc*) NIM_NIL));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes));
	{
		NU64 i_2;
		NU64 colontmp_;
		NU64 res;
		i_2 = (NU64)0;
		colontmp_ = (NU64)0;
		nimln_(65, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		colontmp_ = ((NU64) (nvr));
		nimln_(115, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
		res = 0ULL;
		{
			nimln_(116, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
			while (1) {
				NimStringDesc* tmp;
				NimStringDesc* fmtRes_2;
				NU32 T33_;
				NU32 T34_;
				if (!((NU64)(res) < (NU64)(colontmp_))) goto LA20;
				nimln_(65, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				i_2 = res;
				nimln_(66, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				{
					NU32 T23_;
					NIM_BOOL T24_;
					T23_ = (NU32)0;
					T23_ = X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA(vr, i_2);
					T24_ = (NIM_BOOL)0;
					T24_ = vrOutOfRange__UhcMWpzGPUrXCK9cH9a20zjg(comp, "fmi2SetBoolean", T23_, ((int) 0));
					if (!T24_) goto LA25_;
					nimln_(67, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
					result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
					goto BeforeRet_;
				}
				LA25_: ;
				tmp = (NimStringDesc*)0;
				nimln_(70, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				{
					NI32 T29_;
					T29_ = (NI32)0;
					T29_ = X5BX5D___JS6FVIsrpB7DXYGSQvzqew(value, i_2);
					if (!(((NI32) 0) < T29_)) goto LA30_;
					nimln_(71, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
					tmp = copyString(((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_8));
				}
				goto LA27_;
				LA30_: ;
				{
					nimln_(73, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
					tmp = copyString(((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_9));
				}
				LA27_: ;
				nimln_(74, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
				nimln_(74, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				fmtRes_2 = rawNewString(((NI) 54));
				fmtRes_2 = resizeString(fmtRes_2, 18);
appendString(fmtRes_2, ((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_10));
				nimln_(550, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/core/macros.nim");
				T33_ = (NU32)0;
				T33_ = X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA(vr, i_2);
				nimln_(74, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				formatValue__C31L3FTGCD9awB6j0rwrtEQ((&fmtRes_2), T33_, ((NimStringDesc*) NIM_NIL));
				fmtRes_2 = resizeString(fmtRes_2, 4);
appendString(fmtRes_2, ((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_4));
				formatValue__3zjq9csYPBcIN7AqvyU5ZLA((&fmtRes_2), tmp, ((NimStringDesc*) NIM_NIL));
				filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes_2));
				nimln_(75, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
				T34_ = (NU32)0;
				T34_ = X5BX5D___jBY9cA7wSqMPPCC64jVqw9aA(vr, i_2);
				(*comp).b[T34_] = X5BX5D___JS6FVIsrpB7DXYGSQvzqew(value, i_2);
				nimln_(118, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
				res += ((NI) 1);
			} LA20: ;
		}
	}
	nimln_(77, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		if (!((NU64)(((NU) 0)) < (NU64)(nvr))) goto LA37_;
		nimln_(78, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		(*comp).isDirtyValues = ((NI32) 1);
	}
	LA37_: ;
	nimln_(80, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg, fmi2SetString)(void* c, NU32* vr, size_t nvr, NCSTRING* value) {
	tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg result;
	tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w* comp;
	NimStringDesc* fmtRes;
	nimfr_("fmi2SetString", "/home/jose/src/fmi.nim/src/prueba/setters.nim");
{	result = (tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg)0;
	nimln_(85, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	comp = ((tyObject_ModelInstance__7UjX9aPnXtrm0op9cdZeQ9a0w*) (c));
	nimln_(86, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = invalidState__CFARkdpiNWnLYTkNRNqeNA(comp, "fmi2SetString", ((tyEnum_ModelState__ghm8c7EoWwf9a6hsxvVwGHg) 2));
		if (!T3_) goto LA4_;
		nimln_(87, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(88, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = ((NU64)(((NU) 0)) < (NU64)(nvr));
		if (!(T8_)) goto LA9_;
		T8_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2SetString", "vr[]", ((void*) (vr)));
		LA9_: ;
		if (!T8_) goto LA10_;
		nimln_(89, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA10_: ;
	nimln_(90, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = ((NU64)(((NU) 0)) < (NU64)(nvr));
		if (!(T14_)) goto LA15_;
		T14_ = nullPointer__XwrYJ3AKbQGv6XbV79casAA(comp, "fmi2SetString", "value[]", ((void*) (value)));
		LA15_: ;
		if (!T14_) goto LA16_;
		nimln_(91, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
		result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 3);
		goto BeforeRet_;
	}
	LA16_: ;
	nimln_(92, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	nimln_(578, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/pure/strformat.n"
"im");
	nimln_(92, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	fmtRes = rawNewString(((NI) 36));
	fmtRes = resizeString(fmtRes, 21);
appendString(fmtRes, ((NimStringDesc*) &TM__2S5MsC5486JvBpMWRxckKQ_11));
	formatValue__fFZs9aygbVmQlR35NW07Gbg((&fmtRes), nvr, ((NimStringDesc*) NIM_NIL));
	filteredLog__lw3suybQ5yRVSDxTrBDwWg(comp, ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0), ((int) 2), nimToCStringConv(fmtRes));
	nimln_(127, "/home/jose/src/fmi.nim/src/prueba/setters.nim");
	result = ((tyEnum_fmi2Status__OVS3o9aYFCNieKrbEe9aZwQg) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
