/* Generated by Nim Compiler v1.4.2 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3  -fPIC  -I/home/jose/.choosenim/toolchains/nim-1.4.2/lib -I/home/jose/src/fmi.nim/src/prueba -o /home/jose/src/fmi.nim/src/prueba/.cache/stdlib_formatfloat.nim.c.o /home/jose/src/fmi.nim/src/prueba/.cache/stdlib_formatfloat.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, writeToBuffer__Nntp3gW9b170LCR9cOWNy1tg)(NIM_CHAR* buf, NCSTRING value);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, writeToBuffer__Nntp3gW9b170LCR9cOWNy1tg)(NIM_CHAR* buf, NCSTRING value) {
	NI i;
	nimfr_("writeToBuffer", "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
	nimln_(14, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
	i = ((NI) 0);
	{
		nimln_(15, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		while (1) {
			if (!!(((NU8)(value[i]) == (NU8)(0)))) goto LA2;
			nimln_(16, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
			buf[(i)- 0] = value[i];
			nimln_(17, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
			i += ((NI) 1);
		} LA2: ;
	}
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, writeFloatToBuffer__UrA9aquvUwHFUFx78eUQk3A)(NIM_CHAR* buf, NF value) {
	NI result;
	NI n;
	int T1_;
	NIM_BOOL hasDot;
	nimfr_("writeFloatToBuffer", "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
	result = (NI)0;
	nimln_(32, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
	T1_ = (int)0;
	T1_ = sprintf(((NCSTRING) (buf)), "%.16g", value);
	n = ((NI) (T1_));
	nimln_(33, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
	hasDot = NIM_FALSE;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(34, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		colontmp_ = (NI)(n - ((NI) 1));
		nimln_(77, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
		res = ((NI) 0);
		{
			nimln_(78, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
			while (1) {
				if (!(res <= colontmp_)) goto LA4;
				nimln_(34, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
				i = res;
				nimln_(35, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
				{
					if (!((NU8)(buf[(i)- 0]) == (NU8)(44))) goto LA7_;
					nimln_(36, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
					buf[(i)- 0] = 46;
					nimln_(37, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
					hasDot = NIM_TRUE;
				}
				goto LA5_;
				LA7_: ;
				{
					nimln_(38, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
					if (!(((NU8)(buf[(i)- 0])) >= ((NU8)(97)) && ((NU8)(buf[(i)- 0])) <= ((NU8)(122)) || ((NU8)(buf[(i)- 0])) >= ((NU8)(65)) && ((NU8)(buf[(i)- 0])) <= ((NU8)(90)) || ((NU8)(buf[(i)- 0])) == ((NU8)(46)))) goto LA10_;
					nimln_(39, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
					hasDot = NIM_TRUE;
				}
				goto LA5_;
				LA10_: ;
				LA5_: ;
				nimln_(80, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/iterators"
"_1.nim");
				res += ((NI) 1);
			} LA4: ;
		}
	}
	nimln_(40, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
	{
		if (!!(hasDot)) goto LA14_;
		nimln_(41, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		buf[(n)- 0] = 46;
		nimln_(42, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		buf[((NI)(n + ((NI) 1)))- 0] = 48;
		nimln_(43, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		buf[((NI)(n + ((NI) 2)))- 0] = 0;
		nimln_(44, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		result = (NI)(n + ((NI) 2));
	}
	goto LA12_;
	LA14_: ;
	{
		nimln_(46, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		result = n;
	}
	LA12_: ;
	nimln_(50, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
	{
		if (!(((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(110)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(78)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(68)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(100)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(41)))) goto LA19_;
		nimln_(51, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		writeToBuffer__Nntp3gW9b170LCR9cOWNy1tg(buf, "nan");
		nimln_(52, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		result = ((NI) 3);
	}
	goto LA17_;
	LA19_: ;
	{
		nimln_(53, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		if (!((NU8)(buf[((NI)(n - ((NI) 1)))- 0]) == (NU8)(70))) goto LA22_;
		nimln_(54, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
		{
			if (!((NU8)(buf[(((NI) 0))- 0]) == (NU8)(45))) goto LA26_;
			nimln_(55, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
			writeToBuffer__Nntp3gW9b170LCR9cOWNy1tg(buf, "-inf");
			nimln_(56, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
			result = ((NI) 4);
		}
		goto LA24_;
		LA26_: ;
		{
			nimln_(58, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
			writeToBuffer__Nntp3gW9b170LCR9cOWNy1tg(buf, "inf");
			nimln_(59, "/home/jose/.choosenim/toolchains/nim-1.4.2/lib/system/formatflo"
"at.nim");
			result = ((NI) 3);
		}
		LA24_: ;
	}
	goto LA17_;
	LA22_: ;
	LA17_: ;
	popFrame();
	return result;
}
